modified ttrek-init to install to ~/.ttrek/bin/

diff --git a/public/ttrek-init b/public/ttrek-init
--- a/public/ttrek-init
+++ b/public/ttrek-init
@@ -159,25 +159,29 @@ main() {
     ensure mkdir -p "$_dir"
     ensure downloader "$_url" "$_file" "$_arch"
     ensure chmod u+x "$_file"
-    if [ ! -x "$_file" ]; then
-        printf '%s\n' "Cannot execute $_file (likely because of mounting /tmp as noexec)." 1>&2
-        printf '%s\n' "Please copy the file to a location where you can execute binaries and run ./ttrek-init${_ext}." 1>&2
-        exit 1
-    fi
+    local _ttrek_dir="${TTREK_HOME:-$HOME/.ttrek}/bin"
+    ensure mkdir -p "$_ttrek_dir"
+    ensure cp "$_file" "${_ttrek_dir}/ttrek${_ext}"
 
-    if [ "$need_tty" = "yes" ] && [ ! -t 0 ]; then
-        # The installer is going to want to ask for confirmation by
-        # reading stdin.  This script was piped into `sh` though and
-        # doesn't have stdin to pass to its children. Instead we're going
-        # to explicitly connect /dev/tty to the installer's stdin.
-        if [ ! -t 1 ]; then
-            err "Unable to run interactively. Run with -y to accept defaults, --help for additional options"
-        fi
+#    if [ ! -x "$_file" ]; then
+#        printf '%s\n' "Cannot execute $_file (likely because of mounting /tmp as noexec)." 1>&2
+#        printf '%s\n' "Please copy the file to a location where you can execute binaries and run ./ttrek-init${_ext}." 1>&2
+#        exit 1
+#    fi
 
-        ignore "$_file" "$@" < /dev/tty
-    else
-        ignore "$_file" "$@"
-    fi
+#    if [ "$need_tty" = "yes" ] && [ ! -t 0 ]; then
+#        # The installer is going to want to ask for confirmation by
+#        # reading stdin.  This script was piped into `sh` though and
+#        # doesn't have stdin to pass to its children. Instead we're going
+#        # to explicitly connect /dev/tty to the installer's stdin.
+#        if [ ! -t 1 ]; then
+#            err "Unable to run interactively. Run with -y to accept defaults, --help for additional options"
+#        fi
+#
+#        ignore "$_file" "$@" < /dev/tty
+#    else
+#        ignore "$_file" "$@"
+#    fi
 
     local _retval=$?
 
